name: nyumba_mkononi_admin
description: Admin dashboard for Nyumba Mkononi - property approval and analytics.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
